### ISSUE TITLE
Bug 🐛:  default theme change color too

### ISSUE THREAD

**Issue by Abdulrahman-Sallam** [sudoaugustin/vslook#2]
I installed it and was thrilled how easy it was to change the colors to my liking, but I changed a little too much so I can't return to its default colors and change again with care this time. So I uninstall it, to realize that these changes changed my default theme (dark+ default dark) 
![image](https://user-images.githubusercontent.com/95587474/174676849-559927b3-f3d8-4b89-901a-575803611fb8.png)

**Comment by Abdulrahman-Sallam** [comment]
Solve: go to settings.json and delete the edits that the extension made 

PS: I really looking forward to what this extension could make in the future keep going 👍

**Comment by sudoaugustin** [comment]
### I think u didn't close the webpanel after u have done editing. 
All the styles in `setting.json` are made to be disappeared when u close that webpanel.
Also, I wish to do this on vscode close, but the API doesn't support it. But I will try to solve this issue for a smooth user experience.

Future plans are to help theme creators to export their themes and support changing product icon themes.
