### ISSUE TITLE
VSLook:Edit error in VSCodium but not VSCode

### ISSUE THREAD

**Issue by ghost** [sudoaugustin/vslook#6]
Message: "Command 'VSLook: Edit' resulting in an error (Unexpected token u in JSON at postion 0)"

VSLook Version: v0.3.1; note: Code appends 'Preview' to version, Codium does not

VSCode (OK):
Version: 1.70.0
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:48.541Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.15.0-41-generic

Codium (Not OK):
Version: 1.70.0
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-05T11:26:33.437Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.15.0-41-generic

OS:
System:
  Kernel: 5.15.0-41-generic x86_64 bits: 64 compiler: gcc v: 11.2.0 Desktop: Cinnamon 5.4.9
    tk: GTK 3.24.33 dm: LightDM Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop System: Dell product: OptiPlex 7020 v: 00 serial: <superuser required> Chassis:
    type: 6 serial: <superuser required>
  Mobo: Dell model: 0F5C5X v: A00 serial: <superuser required> BIOS: Dell v: A10
    date: 09/22/2016
Battery:
  Device-1: hidpp_battery_0 model: Logitech M570 serial: <filter> charge: 40% status: Discharging
CPU:
  Info: quad core model: Intel Core i5-4590 bits: 64 type: MCP arch: Haswell rev: 3 cache:
    L1: 256 KiB L2: 1024 KiB L3: 6 MiB
  Speed (MHz): avg: 2348 high: 2788 min/max: 800/3700 cores: 1: 1167 2: 2661 3: 2788 4: 2778
    bogomips: 26336
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: AMD Oland [Radeon HD 8570 / R5 430 OEM R7 240/340 Radeon 520 OEM] vendor: Dell
    driver: radeon v: kernel pcie: speed: 8 GT/s lanes: 8 ports: active: DVI-I-1 empty: DP-1
    bus-ID: 01:00.0 chip-ID: 1002:6611
  Device-2: Realtek RTL2838 DVB-T type: USB driver: dvb_usb_rtl28xxu,rtl2832_sdr bus-ID: 3-8:4
    chip-ID: 0bda:2838
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: ati,radeon
    unloaded: fbdev,modesetting,vesa gpu: radeon display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96
  Monitor-1: DVI-0 mapped: DVI-I-1 model: Acer H233H res: 1920x1080 dpi: 96 diag: 585mm (23")
  OpenGL: renderer: AMD OLAND (LLVM 13.0.1 DRM 2.50 5.15.0-41-generic) v: 4.5 Mesa 22.0.5
    direct render: Yes
Audio:
  Device-1: Intel 8 Series/C220 Series High Definition Audio vendor: Dell driver: snd_hda_intel
    v: kernel bus-ID: 00:1b.0 chip-ID: 8086:8c20
  Device-2: AMD Oland/Hainan/Cape Verde/Pitcairn HDMI Audio [Radeon HD 7000 Series] vendor: Dell
    driver: snd_hda_intel v: kernel pcie: speed: 8 GT/s lanes: 8 bus-ID: 01:00.1 chip-ID: 1002:aab0
  Sound Server-1: ALSA v: k5.15.0-41-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Ethernet I217-LM vendor: Dell driver: e1000e v: kernel port: f040
    bus-ID: 00:19.0 chip-ID: 8086:153a
  IF: eno1 state: up speed: 1000 Mbps duplex: full mac: <filter>
Drives:
  Local Storage: total: 1.93 TiB used: 1.72 TiB (89.4%)
  ID-1: /dev/sda vendor: Western Digital model: WDS100T2B0A-00SM50 size: 931.51 GiB
    speed: 6.0 Gb/s serial: <filter>
  ID-2: /dev/sdb vendor: Samsung model: SSD 840 EVO 120GB size: 111.79 GiB speed: 6.0 Gb/s
    serial: <filter>
  ID-3: /dev/sdc type: USB vendor: Western Digital model: WD My Passport 25E1 size: 931.48 GiB
    serial: <filter>
Partition:
  ID-1: / size: 98.44 GiB used: 15.33 GiB (15.6%) fs: ext4 dev: /dev/sdb1
  ID-2: /home size: 915.82 GiB used: 662.06 GiB (72.3%) fs: ext4 dev: /dev/sda1
Swap:
  ID-1: swap-1 type: partition size: 11.21 GiB used: 437 MiB (3.8%) priority: -2 dev: /dev/sdb2
Sensors:
  System Temperatures: cpu: 29.8 C mobo: 27.8 C gpu: radeon temp: 40.0 C
  Fan Speeds (RPM): N/A
Repos:
  Packages: apt: 3003
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/jonaski-strawberry-jammy.list
    1: deb http: //ppa.launchpad.net/jonaski/strawberry/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/microsoft-prod.list
    1: deb [arch=amd64,arm64,armhf] https: //packages.microsoft.com/ubuntu/22.04/prod jammy main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com vanessa main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/vscode.list
    1: deb [arch=amd64,arm64,armhf] http: //packages.microsoft.com/repos/code stable main
Info:
  Processes: 261 Uptime: 11h 22m Memory: 10.65 GiB used: 3.49 GiB (32.8%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.2.0 alt: 11 Client: Unknown python client inxi: 3.3.13

**Comment by sudoaugustin** [comment]
Sorry, I will be focusing VSLook only to work with VSCode.

**Comment by Lucas-Lantimant** [comment]
I am having the following error when using vslook clone: currentTheme is not interable
