### ISSUE TITLE
I can't open the Vslook Editor interface in vscode, the following is the screenshot

### ISSUE THREAD

**Issue by youkei-zzz** [sudoaugustin/vslook#7]
I can't open the Vslook Editor interface in vscode, the following is the screenshot.
![image](https://user-images.githubusercontent.com/101049479/195507135-bd8619e3-da30-4cae-9f89-544808bce413.png)

**Comment by sudoaugustin** [comment]
@youkei-zzz Did u tried reloading your vscode or are u opening vscode in development mode?

**Comment by sudoaugustin** [comment]
Since no reply from the issue creator, I'll close this issue

**Comment by PiedPierre** [comment]
J'ai le même problème. J'ai tenté de désinstaller VSLook et de le re-installer. Rien ne change. J'ai fermé et ouvert VSC rien ne change. Je ne sais pas ce qu'est le mode développement, je débute un peu, je ne pense pas y avoir touché.

**Comment by PiedPierre** [comment]
Mince, j'ai pas la permission de ré-ouvrir le problème. C'est dommage, j'aimais bien cette extension mais je ne peux plus l'utiliser. Je précise être sous Win11 pro thème sombre à la base.
